// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://konzfjoknohzayqvcdja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvbnpmam9rbm9oemF5cXZjZGphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTk3NzcsImV4cCI6MjA2OTU5NTc3N30.mINp4TWy3A4uGYq39lSaBywFDoYqoWLXAYHu8Su75wM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});